version: '3.4'

services:
  aspnet_api_template.api:
    image: ${DOCKER_REGISTRY-}aspnetapitemplateapi
    build:
      context: .
      dockerfile: AspNet_API_Template.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=3000
      - ASPNETCORE_HTTP_PORTS=3001
    ports:
      - 3000:3000
      - 3001:3001
